name: First workflow
on: push
jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
            - name: Build the app
              run: |
                  sleep 3
                  echo "building the app ..." > app.txt
    test-job:
        needs: build-job
        runs-on: ubuntu-latest
        steps:
            - name: Test the app
              run: |
                  sleep 3
                  cat app.txt
                  echo "testing the app ..." >> app.txt
    deploy-job:
        needs: test-job
        runs-on: ubuntu-latest
        steps:
            - name: Deploy the app
              run: |
                  sleep 1
                  cat app.txt
                  echo "deploying the app ..." >> app.txt