name: Build and deploy
on: workflow_dispatch
env:
            CONTAINER_REGISTRY: docker.io
            IMAGE_NAME: app
jobs: 
  docker-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Build the image
        timeout-minutes: 1
        run: sleep 10000

      - name: Login
        run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password= ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the image
        run: echo docekr push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME
  
  deploy-job:
    needs: docker-job
    runs-on: ubuntu-latest
    steps:
      - name: Run the app
        run: echo docker run $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME


# name: First workflow
# on: push
# jobs:
#     build-job:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Build the app
#               run: |
#                   sleep 3
#                   echo "building the app ..." > app.txt
            
#             - name: Upload the app.txt file
#               uses: actions/upload-artifact@v4
#               with:
#                     name: app-text-file
#                     path: app.txt

#     test-job:
#         needs: build-job
#         runs-on: ubuntu-latest
#         steps:
#             - name: Download the app.txt file
#               uses: actions/download-artifact@v5
#               with:
#                     name: app-text-file

#             - name: Test the app
#               run: |
#                   sleep 3
#                   cat app.txt
#                   echo "testing the app ..."
#     deploy-job:
#         needs: test-job
#         runs-on: ubuntu-latest
#         steps:
#             - name: Download the app.txt file
#               uses: actions/download-artifact@v5
#               with:
#                     name: app-text-file

#             - name: Deploy the app
#               run: |
#                   sleep 1
#                   cat app.txt
#                   echo "deploying the app ..."