name: First workflow
on: push
jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
            - name: Build the app
              run: |
                  sleep 3
                  echo "building the app ..." > app.txt
            
            - name: Upload the app.txt file
              uses: actions/upload-artifact@v4
              with:
                    name: app-text-file
                    path: app.txt

    test-job:
        needs: build-job
        runs-on: ubuntu-latest
        steps:
            - name: Download the app.txt file
              uses: actions/download-artifact@v5
              with:
                    name: app-text-file

            - name: Test the app
              run: |
                  sleep 3
                  cat app.txt
                  echo "testing the app ..."
    deploy-job:
        needs: test-job
        runs-on: ubuntu-latest
        steps:
            - name: Download the app.txt file
              uses: actions/download-artifact@v5
              with:
                    name: app-text-file

            - name: Deploy the app
              run: |
                  sleep 1
                  cat app.txt
                  echo "deploying the app ..."